# -*- coding: utf-8 -*-
"""automate_muhammad_aiyub.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Cme4Upo_z_kwrDGSTYVFXjRd0O9Qt2T

# automate_muhammad_aiyub.py
"""

# automate_muhammad_aiyub.py
import pandas as pd
import numpy as np
import joblib
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import os
import warnings
warnings.filterwarnings('ignore')

def run_preprocessing(train_path, val_path, output_dir='namadataset_preprocessing'):
    """
    Fungsi untuk melakukan preprocessing otomatis dari file CSV mentah
    dan menyimpan hasil siap latih beserta preprocessor-nya.
    """
    # 1. Load data
    print(f"Memuat data dari {train_path} dan {val_path}")
    df_train = pd.read_csv(train_path)
    df_val = pd.read_csv(val_path)

    # 2. Pisahkan target (kolom 'label')
    target_col = 'label'
    X_train = df_train.drop(columns=[target_col])
    y_train = df_train[target_col]

    # Untuk validation, cek apakah ada kolom 'label'
    if target_col in df_val.columns:
        X_val = df_val.drop(columns=[target_col])
        y_val = df_val[target_col]
    else:
        X_val = df_val.copy()
        y_val = None
        print("⚠️  Validation set tidak memiliki kolom 'label'. Hanya fitur yang akan diproses.")

    # 3. Identifikasi tipe kolom
    num_cols = X_train.select_dtypes(include=['int64', 'float64']).columns.tolist()
    cat_cols = X_train.select_dtypes(include=['object']).columns.tolist()

    print(f"Kolom Numerik: {len(num_cols)}, Kolom Kategorikal: {len(cat_cols)}")

    # 4. Buat pipeline preprocessing
    num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ])

    cat_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
    ])

    preprocessor = ColumnTransformer([
        ('num', num_pipeline, num_cols),
        ('cat', cat_pipeline, cat_cols)
    ])

    # 5. Fit dan transform
    print("Melakukan preprocessing...")
    X_train_processed = preprocessor.fit_transform(X_train)
    X_val_processed = preprocessor.transform(X_val)

    # 6. Simpan hasil
    os.makedirs(output_dir, exist_ok=True)
    np.save(f'{output_dir}/X_train_processed.npy', X_train_processed)
    np.save(f'{output_dir}/X_val_processed.npy', X_val_processed)
    np.save(f'{output_dir}/y_train.npy', y_train.values)
    if y_val is not None:
        np.save(f'{output_dir}/y_val.npy', y_val.values)
    joblib.dump(preprocessor, f'{output_dir}/preprocessor.pkl')

    print(f"✅ Preprocessing selesai! Semua file tersimpan di folder '{output_dir}'.")
    return X_train_processed, X_val_processed, y_train, y_val

if __name__ == "__main__":
    # Jalankan langsung jika file dieksekusi
    run_preprocessing('fraud_detection_train.csv', 'fraud_detection_val.csv')