name: Preprocessing Automation

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pandas numpy scikit-learn joblib

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_muhammad_aiyub.py

    # ⭐ INI BAGIAN BARU: UPLOAD ARTIFACT, BUKAN COMMIT KE REPO
    - name: Upload processed data as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: processed-dataset-muhammad-aiyub
        path: namadataset_preprocessing/
        retention-days: 7
